"""initial schema

Revision ID: f86827dbb08a
Revises:
Create Date: 2026-07-25 08:19:36.966679+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f86827dbb08a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_role", sa.String(length=40), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index("ix_audit_created", "audit_events", ["created_at"], unique=False)
    op.create_index("ix_audit_entity", "audit_events", ["entity_type", "entity_id"], unique=False)
    op.create_table(
        "idempotency_records",
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint", sa.String(length=120), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint("idempotency_key", "endpoint", "actor_id", name="uq_idempotency_scope"),
    )
    op.create_table(
        "outbox_events",
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "processed", "failed", name="outboxstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        "ix_outbox_status_created", "outbox_events", ["status", "created_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("customer", "merchant", "admin", name="userrole", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "merchants",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "suspended", name="merchantstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_merchants_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchants")),
    )
    op.create_index(
        op.f("ix_merchants_owner_user_id"), "merchants", ["owner_user_id"], unique=False
    )
    op.create_table(
        "experiences",
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("destination", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "published",
                "archived",
                name="experiencestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("base_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "cancellation_policy",
            sa.Enum(
                "fully_refundable_until_24_hours",
                "non_refundable",
                "flexible_until_start",
                name="cancellationpolicy",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_experiences_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiences")),
        sa.UniqueConstraint("slug", name=op.f("uq_experiences_slug")),
    )
    op.create_index(
        op.f("ix_experiences_merchant_id"), "experiences", ["merchant_id"], unique=False
    )
    op.create_index(
        "ix_experiences_search", "experiences", ["destination", "category", "status"], unique=False
    )
    op.create_table(
        "experience_slots",
        sa.Column("experience_id", sa.Uuid(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("reserved_quantity", sa.Integer(), nullable=False),
        sa.Column("confirmed_quantity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "sold_out", "closed", name="slotstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("capacity >= 0", name=op.f("ck_experience_slots_capacity_non_negative")),
        sa.CheckConstraint(
            "confirmed_quantity >= 0", name=op.f("ck_experience_slots_confirmed_non_negative")
        ),
        sa.CheckConstraint(
            "reserved_quantity + confirmed_quantity <= capacity",
            name=op.f("ck_experience_slots_committed_within_capacity"),
        ),
        sa.CheckConstraint(
            "reserved_quantity >= 0", name=op.f("ck_experience_slots_reserved_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["experience_id"],
            ["experiences.id"],
            name=op.f("fk_experience_slots_experience_id_experiences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experience_slots")),
    )
    op.create_index(
        "ix_experience_slots_experience_start",
        "experience_slots",
        ["experience_id", "starts_at"],
        unique=False,
    )
    op.create_table(
        "partner_inventory_updates",
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("external_update_id", sa.String(length=120), nullable=False),
        sa.Column("slot_id", sa.Uuid(), nullable=False),
        sa.Column("requested_capacity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "accepted", "rejected", name="partnerupdatestatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("validation_result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_partner_inventory_updates_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["experience_slots.id"],
            name=op.f("fk_partner_inventory_updates_slot_id_experience_slots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partner_inventory_updates")),
        sa.UniqueConstraint(
            "merchant_id", "external_update_id", name="uq_partner_update_external_id"
        ),
    )
    op.create_table(
        "reservations",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("slot_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "converted",
                "expired",
                "cancelled",
                name="reservationstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_reservations_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["users.id"],
            name=op.f("fk_reservations_customer_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["experience_slots.id"],
            name=op.f("fk_reservations_slot_id_experience_slots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservations")),
    )
    op.create_index("ix_reservations_customer", "reservations", ["customer_id"], unique=False)
    op.create_index(
        "ix_reservations_status_expiry", "reservations", ["status", "expires_at"], unique=False
    )
    op.create_table(
        "bookings",
        sa.Column("booking_reference", sa.String(length=20), nullable=False),
        sa.Column("reservation_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("slot_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending_payment",
                "confirmed",
                "cancellation_pending",
                "cancelled",
                "payment_failed",
                name="bookingstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_bookings_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["users.id"],
            name=op.f("fk_bookings_customer_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_bookings_reservation_id_reservations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["experience_slots.id"],
            name=op.f("fk_bookings_slot_id_experience_slots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
        sa.UniqueConstraint("booking_reference", name=op.f("uq_bookings_booking_reference")),
        sa.UniqueConstraint("reservation_id", name=op.f("uq_bookings_reservation_id")),
    )
    op.create_index("ix_bookings_customer", "bookings", ["customer_id"], unique=False)
    op.create_index("ix_bookings_slot", "bookings", ["slot_id"], unique=False)
    op.create_table(
        "payment_attempts",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("provider_reference", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "succeeded", "failed", name="paymentstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("event_id", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_payment_attempts_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_attempts")),
    )
    op.create_index("ix_payment_attempts_booking", "payment_attempts", ["booking_id"], unique=False)
    op.create_index(
        "uq_payment_attempts_event_id",
        "payment_attempts",
        ["event_id"],
        unique=True,
        postgresql_where="event_id IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_payment_attempts_event_id",
        table_name="payment_attempts",
        postgresql_where="event_id IS NOT NULL",
    )
    op.drop_index("ix_payment_attempts_booking", table_name="payment_attempts")
    op.drop_table("payment_attempts")
    op.drop_index("ix_bookings_slot", table_name="bookings")
    op.drop_index("ix_bookings_customer", table_name="bookings")
    op.drop_table("bookings")
    op.drop_index("ix_reservations_status_expiry", table_name="reservations")
    op.drop_index("ix_reservations_customer", table_name="reservations")
    op.drop_table("reservations")
    op.drop_table("partner_inventory_updates")
    op.drop_index("ix_experience_slots_experience_start", table_name="experience_slots")
    op.drop_table("experience_slots")
    op.drop_index("ix_experiences_search", table_name="experiences")
    op.drop_index(op.f("ix_experiences_merchant_id"), table_name="experiences")
    op.drop_table("experiences")
    op.drop_index(op.f("ix_merchants_owner_user_id"), table_name="merchants")
    op.drop_table("merchants")
    op.drop_table("users")
    op.drop_index("ix_outbox_status_created", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_table("idempotency_records")
    op.drop_index("ix_audit_entity", table_name="audit_events")
    op.drop_index("ix_audit_created", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
